version: '3.7'
services:
  crm:
    build:
      context: .
    env_file:
      - .env
    command: ["/crm/docker/app.sh"]
    ports:
      - 8000:8000
    depends_on:
      - db
      - redis

  db:
    image: postgres:15
    container_name: crm_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    env_file:
      - .env

  redis:
    image: redis:7
    container_name: crm_redis

volumes:
  postgres_data: